"""adding order_prods table

Revision ID: 5ad5ff023159
Revises: 6e68b37f4342
Create Date: 2024-03-14 15:47:36.683719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ad5ff023159'
down_revision: Union[str, None] = '6e68b37f4342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_prods',
    sa.Column('order_prods_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('prod_id', sa.Integer(), nullable=True),
    sa.Column('prods_quantity', sa.Integer(), nullable=True),
    sa.Column('order_price', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['prod_id'], ['products.prod_id'], ),
    sa.PrimaryKeyConstraint('order_prods_id')
    )
    op.create_index(op.f('ix_order_prods_order_prods_id'), 'order_prods', ['order_prods_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_prods_order_prods_id'), table_name='order_prods')
    op.drop_table('order_prods')
    # ### end Alembic commands ###
