"""Database creation

Revision ID: 6e68b37f4342
Revises: 
Create Date: 2024-03-07 10:27:11.414849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e68b37f4342'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('phone')
    )
    
    op.create_table('restaurants',
    sa.Column('rest_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=40), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('working_time', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('rest_id')
    )
    
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('rest_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )


    op.create_table('couriers',
    sa.Column('courier_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('rating', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('geolocation', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('courier_id')
    )
    
    
    
    

    
    

    
    

    op.create_table('order_details',
    sa.Column('order_det_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('order_det_id')
    )
   
    

    op.create_table('products',
    sa.Column('prod_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rest_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('prod_id')
    )
    
    
    op.create_index(op.f('ix_clients_client_id'), 'clients', ['client_id'], unique=False)
    op.create_index(op.f('ix_restaurants_rest_id'), 'restaurants', ['rest_id'], unique=False)
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_couriers_courier_id'), 'couriers', ['courier_id'], unique=False)
    op.create_index(op.f('ix_order_details_order_det_id'), 'order_details', ['order_det_id'], unique=False)
    op.create_index(op.f('ix_products_prod_id'), 'products', ['prod_id'], unique=False)
    

    op.create_foreign_key('fk_orders_clients', 'orders', 'clients', ['client_id'], ['client_id'])
    op.create_foreign_key('fk_orders_couriers', 'orders', 'couriers', ['courier_id'], ['courier_id'])
    op.create_foreign_key('fk_orders_restaurants', 'orders', 'restaurants', ['rest_id'], ['rest_id'])
    op.create_foreign_key('fk_couriers_clients', 'couriers', 'clients', ['client_id'], ['client_id'])
    op.create_foreign_key('fk_couriers_orders', 'couriers', 'orders', ['order_id'], ['order_id'])
    op.create_foreign_key('fk_order_details_orders', 'order_details', 'orders', ['order_id'], ['order_id'])
    op.create_foreign_key('fk_products_restaurants', 'products', 'restaurants', ['rest_id'], ['rest_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_prod_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_order_details_order_det_id'), table_name='order_details')
    op.drop_table('order_details')
    op.drop_index(op.f('ix_restaurants_rest_id'), table_name='restaurants')
    op.drop_table('restaurants')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_couriers_courier_id'), table_name='couriers')
    op.drop_table('couriers')
    op.drop_index(op.f('ix_clients_client_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
